### ISSUE TITLE
Can you show some scenarios  when to using java-concurrent tracing？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [opentracing-contrib/java-concurrent#22]
Can you show some scenarios use this library.  Thank you very much.

**Comment by jpkrohling** [comment]
Docs would really be improved, but the unit tests are a good source of examples. Like this:

https://github.com/opentracing-contrib/java-concurrent/blob/459cf967b04d6c85af8e6feaf4cc0a9454d7702d/src/test/java/io/opentracing/contrib/concurrent/TracedRunnableTest.java#L16
