### ISSUE TITLE
How to pass parent context with TracedExecutor Service

### ISSUE THREAD

**Issue by kameshsampath** [opentracing-contrib/java-concurrent#3]
currently the traced executor service - creates new spans, wondering is there a way we can extend it to use parentSpanContext if any, typically used in Chaining scenarios. 

Similar to 

* https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
* https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LocalComponentTraceRunnable.java 
* https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/SpanContinuingTraceCallable.java

Ref: https://github.com/opentracing-contrib/java-spring-cloud/issues/35

**Comment by pavolloffay** [comment]
This instrumentation does not create any spans, it just propagates span from parent thread to one created by `ExecutorService`. 

I will work on https://github.com/opentracing-contrib/java-spring-cloud/issues/35 soon and use this impl there.

**Comment by kameshsampath** [comment]
Thanks @pavolloffay actually I have started a partial implementation let me see if I can PR that you, does that work for you?

**Comment by pavolloffay** [comment]
@kameshsampath I am closing this, feel free to reopen if necessary.
