### ISSUE TITLE
Create new span if paren span is missing

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-concurrent#6]
This library currently, only passes active span from parent thread to submitted runnable/callable. If there is no parent span it does nothing. 

We should consider creating a new span if there is no parent span.

**Comment by objectiser** [comment]
Not sure - I think the role of this library is just to propagate the trace context, not to assume that a span should exist. If the application wants some form of bounding scope/span, then they should ensure it is created through other instrumentations or explicitly by the application itself.

**Comment by pavolloffay** [comment]
Executors are usually used for time-consuming tasks, therefore having a span which wraps the whole invocation helps you to understand latency problems. Not even saying that In some situations, there won't be parent span (e.g. no servlet environment) in this situation this library does not bring you any value.  A specific use case is Executor instrumentation in Spring. It can be used without web package.

Creating a span should be optional. It would be a boolean flag in executor constructor whether to create a span or not.

**Comment by malafeev** [comment]
fixed via https://github.com/opentracing-contrib/java-concurrent/pull/13
can be closed now
